import { Project } from './types';

export const projects: Project[] = [
  // 1행 — 블루에서 퍼플로 이어지는 대표 작업
  {
    id: 1,
    title: "JAPAN MOBILE",
    category: "APP",
    year: "2026",
    imageUrl: "/assets/portfolio/2.App/HouRensoPro.png",
    description:"일본 특유 업무 보고,연락,상담에 맞춘 KPI 시스템 앱",
    images: ["/assets/portfolio/2.App/HouRensoPro - portfolio.png"],
    importance: 1,
  },
  {
    id: 3,
    title: "SUBCULTURE UI",
    category: "GAME",
    year: "2025",
    imageUrl: "/assets/portfolio/1.Game/Subculture(UI).png",
    description:"SUBCULTURE 캐릭터 수집 1인칭 FPS로 캐릭터, 무기를 선택하여 결투",
    images: ["/assets/portfolio/1.Game/Subculture(UI)-portfolio.png"],
    importance: 1,
  },
  {
    id: 4,
    title: "AETHERIA UI System",
    category: "GAME",
    year: "2025",
    imageUrl: "/assets/portfolio/1.Game/RPG(UI).png",
    description:"RPG UI 디자인 하늘 전장에서 싸우는 여신들 리뉴얼작업중",
    images: ["/assets/portfolio/1.Game/RPGUI(리뉴얼작업중).png"],
    importance: 1,
  },
   {
    id: 15,
    title: "FPS UI",
    category: "GAME",
    year: "2025",
    imageUrl: "/assets/portfolio/1.Game/FPS(UI).png",
    description:"4:4 협동 FPS UI ",
    images: ["/assets/portfolio/1.Game/FPSUI.png"],
    importance: 1,
    showInMain: false,
  },

  // 2행 — 어두운 게임 비주얼에서 레드 계열로 연결
  {
    id: 6,
    title: "Auto Chess",
    category: "GAME",
    year: "2025",
    imageUrl: "/assets/portfolio/4.Dev/Image Sequence.png",
    videoUrl: [
      "/assets/portfolio/4.Dev/Movie_001.mp4",
      "/assets/portfolio/4.Dev/Movie_002.mp4",
    ],
    description:"Unity 기반 자동 전투 전략 게임 입니다. Kenney 리소스 활용한 타일 전장 맵구성, ScriptableObject 로 UI 구성 유닛 배치 및 상호작용 개발, AI전투 시스템",
    images: ["/assets/portfolio/4.Dev/StratEdge_자동 전투 전략 게임.png"],
    importance: 3,
  },
  {
    id: 7,
    title: "XR GAME (team project)",
    category: "XR",
    year: "2025",
    imageUrl: "/assets/portfolio/4.Dev/귀도행.png",
    videoUrl: ["/assets/portfolio/4.Dev/귀도행 시연영상.mp4"],
    description:"Unity 기반 XR 프로젝트입니다. XR 플레이어 컨트롤 개발, UI 개발, 그리고 각종 디자인 작업",
    images: ["/assets/portfolio/4.Dev/귀도행VR개발.png"],
    importance: 3,
  },
  {
    id: 2,
    title: "Banking App",
    category: "APP",
    year: "2021",
    imageUrl: "/assets/portfolio/2.App/키움증권 영웅문.png",
    description:"옛날(2020) 키움 영웅앱을 리디자인",
    images: ["/assets/portfolio/2.App/키움증권 영웅문-portfolio.png"],
    importance: 3,
  },

  // 3행 — 밝고 컬러풀한 앱·웹 프로젝트
  {
    id: 9,
    title: "GenZ gaming",
    category: "APP",
    year: "2025",
    imageUrl: "/assets/portfolio/2.App/Hype Hype_Redesign.png",
    description:"외국 게임 커뮤니티 앱을 젠지(영피플)를 경향한 리디자인",
    images: ["/assets/portfolio/2.App/Hype Hype_Redesign-portfolio.png"],
    importance: 3,
    showInMain: false,
  },
  {
    id: 8,
    title: "Smart Farm",
    category: "APP",
    year: "2024",
    imageUrl: "/assets/portfolio/2.App/야채팜2.png",
    description:"B2B 농수산물 도매시장 직송 배달 앱 (실시간 가격 측정, 가계부, 알림)",
    images: ["/assets/portfolio/2.App/야채팜-portfolio.png"],
    importance: 3,
    showInMain: false,
  },
  {
    id: 5,
    title: "Dashboard",
    category: "WEB",
    year: "2025",
    imageUrl: "/assets/portfolio/3.대시보드/ABS_ITAM 커버.png",
    description:"내부 자산관리시스템",
    images: ["/assets/portfolio/3.대시보드/ABS-ITAM 자산관리시스템_스타일가이드+디자인.png"],
    importance: 3,
  },
  
  {
    id: 12,
    title: "Public institution WEB",
    category: "WEB",
    year: "2026",
    imageUrl: "/assets/portfolio/5.Web/저출산위원회-커버.png",
    description:"공공기관 홈페이지 개선 방향 반응형작업은 별도로 안되어있습니다.",
    websiteUrl:
    'https://yeni7856.github.io/Public-institution-website/',
    images: ["/assets/portfolio/5.Web/저출산대책위원회-portfolio.png"],
    importance: 1,
  },
  // 4행 — 화이트·블루 실무 대시보드
  {
    id: 14,
    title: "Education WEB",
    category: "WEB",
    year: "2026",
    imageUrl: "/assets/portfolio/5.Web/한국교육진흥원-커버.png",
    description:"공공기관 홈페이지 개선 방향",
    images: ["/assets/portfolio/5.Web/한국보육진흥원-portfolio.png"],
    importance: 3,
    showInMain: false,
  },
  {
    id: 16,
    title: "Electronic",
    category: "WEB",
    year: "2023",
    imageUrl: "/assets/portfolio/2.App/전자송품장.png",
    description:"공공기관 전자송품장 기존 디자인건 리디자인",
    images: ["/assets/portfolio/2.App/전자송품장-portfolio.png"],
    importance: 3,
    showInMain: false,
  },
  {
    id: 10,
    title: "Dashboard",
    category: "WEB",
    year: "2023",
    imageUrl: "/assets/portfolio/3.대시보드/시장동향 대시보드.png",
    description:"농산물 시장동향 대시보드 디자인",
    images: ["/assets/portfolio/3.대시보드/시장동향 대시보드-portfolio.png"],
    importance: 3,
    showInMain: false,
  },
  {
    id: 11,
    title: "Dashboard",
    category: "WEB",
    year: "2023",
    imageUrl: "/assets/portfolio/3.대시보드/시스템관리 대시보드.png",
    description:"내부 시스템 관리 대시보드 디자인",
    images: ["/assets/portfolio/3.대시보드/시스템관리 대시보드-portfolio.png"],
    importance: 3,
    showInMain: false,
  },

  // 추후 WEB 필터에서만
  {
    id: 13,
    title: "2021~2023 WEB UIUX",
    category: "WEB",
    year: "2021-2023",
    imageUrl: "/assets/portfolio/5.Web/WEB UIUX 디자인.png",
    description:"웹 디자인 모음",
    images: ["/assets/portfolio/5.Web/WEB UIUX 디자인-portfolio.png"],
    importance: 1,
    showInMain: false,
  },
];

export const mainProjects = projects.filter((p) => p.showInMain !== false);